# Generated by Django 5.0.7 on 2024-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('fibre', 'Fibre Cables'), ('triple play', 'Triple Play 3-in-1 LED Lights'), ('installation', 'Installation Services')], max_length=100)),
                ('message', models.TextField()),
                ('accepted_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
