# Generated by Django 5.0.7 on 2024-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer_gallery/')),
            ],
        ),
    ]
