# Generated by Django 5.0.1 on 2024-07-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_footergallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='accepted_terms',
        ),
    ]
