# Generated by Django 5.0.1 on 2024-08-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail_url',
        ),
    ]
