# Generated by Django 5.0.1 on 2024-08-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blog_meta_blog_thumbnail_url_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail_url',
        ),
    ]
