# Generated by Django 5.0.1 on 2024-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='investors/'),
        ),
    ]
