# Generated by Django 5.0.1 on 2024-08-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='brief_description',
            field=models.TextField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
