# Generated by Django 5.0.1 on 2024-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_product_description_product_brief_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brief_description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
