# Generated by Django 5.0.1 on 2024-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_product_images_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='sustainability_images/')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
