# Generated by Django 5.0.1 on 2024-08-20 12:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_sustainability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainability',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
