# Generated by Django 5.0.1 on 2024-08-21 07:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_sustainability_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainability',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
