# Generated by Django 5.0.1 on 2024-08-21 11:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_initiative'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
