# Generated by Django 5.0.1 on 2024-08-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_casestudies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStudies',
            new_name='CaseStudy',
        ),
    ]
