# Generated by Django 5.0.1 on 2024-08-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_industrysolutions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustrySolutions',
            new_name='IndustrySolution',
        ),
    ]
