# Generated by Django 5.0.1 on 2024-08-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_rename_industrysolutions_industrysolution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustrySolution',
            new_name='Solution',
        ),
    ]
