# Generated by Django 5.0.1 on 2024-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_rename_industrysolution_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
