# Generated by Django 5.0.1 on 2024-08-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
