# Generated by Django 5.0.1 on 2024-08-22 09:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
