# Generated by Django 5.0.1 on 2024-08-22 10:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_opportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=tinymce.models.HTMLField(max_length=200),
        ),
    ]
