# Generated by Django 5.0.1 on 2024-08-22 10:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_opportunity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=tinymce.models.HTMLField(max_length=250),
        ),
    ]
