# Generated by Django 5.0.1 on 2024-08-26 08:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_opportunity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('message', tinymce.models.HTMLField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
