# Generated by Django 5.0.1 on 2024-08-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
    ]
