# Generated by Django 5.0.1 on 2024-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_rename_sent_at_feedback_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
